  
name: mask_rcnn
channels:
- peterjc123
- menpo
- conda-forge
- defaults
dependencies:
- python=3.5.5
- scipy
- opencv3
- h5py
- imgaug
- scikit-image
- cython
- pip:
  - tensorflow==1.3.0
  - Pillow==5.0.0
  - numpy==1.15.0
  - keras==2.0.8
  - matplotlib